[package]
name = "uart_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.30.0", features = ["unstable"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
serialport = "4.8.1"
